// Loaded into a VM with Model/Chords/Song/Keyboard functions in scope.

assertEq(wrap(12), 0, "wrap 12")
assertEq(wrap(-1), 11, "wrap -1")
assertEq(keyAt(0).major, "C")
assertEq(keyAt(1).major, "G")
assertEq(label(0), "C / Am")
assertEq(diatonic(0).I, "C")
assertEq(diatonic(0).V, "G")
assertEq(diatonic(0).vi, "Am")
assert(inKeyWedge(0, 0), "tonic in wedge")
assert(inKeyWedge(1, 0), "dominant in wedge")
assert(inKeyWedge(11, 0), "subdominant in wedge")
assert(!inKeyWedge(2, 0), "D not in C wedge")
assertEq(triad(0, "major").label, "C")
assertEq(triad(0, "minor").label, "Am")
assertEq(triad(0, "major").notes.length, 3)
assertEq(tonicIndexForSymbol("G"), 1)

var c = parseChord("C")
assert(c.isValid, "parse C")
assertEq(c.chord.notes.join(","), "60,64,67")
assertEq(c.chord.quality, "major")

var cm = parseChord("Cm")
assert(cm.isValid, "parse Cm")
assertEq(cm.chord.quality, "minor")
assertEq(cm.chord.notes.join(","), "60,63,67")

var am = parseChord("Am")
assert(am.isValid, "parse Am")
assertEq(am.chord.quality, "minor")
assertEq(am.chord.notes.join(","), "69,72,76")

var c7 = parseChord("C7")
assert(c7.isValid, "parse C7")
assert(c7.chord.notes.indexOf(70) !== -1, "C7 has Bb")

var cmaj7 = parseChord("Cmaj7")
assert(cmaj7.isValid, "parse Cmaj7")
assertEq(cmaj7.chord.quality, "major")
assert(cmaj7.chord.notes.indexOf(71) !== -1, "Cmaj7 has B")
assertEq(cmaj7.chord.notes.join(","), "60,64,67,71")

var fdim = parseChord("F#dim")
assert(fdim.isValid, "parse F#dim")
assertEq(fdim.chord.quality, "diminished")
assertEq(fdim.chord.notes.join(","), "66,69,72")

var slash = parseChord("G/B")
assert(slash.isValid, "parse G/B")
assert(slash.chord.bass === "B" || slash.chord.bass === "b" || !!slash.chord.bass, "slash bass")

var csus4 = parseChord("Csus4")
assert(csus4.isValid, "parse Csus4")
assertEq(csus4.chord.quality, "sus4")
assertEq(csus4.chord.notes.join(","), "60,65,67")

var csus2 = parseChord("Csus2")
assert(csus2.isValid, "parse Csus2")
assertEq(csus2.chord.quality, "sus2")
assertEq(csus2.chord.notes.join(","), "60,62,67")

var dm9 = parseChord("Dm9")
assert(dm9.isValid, "parse Dm9")
assertEq(dm9.chord.quality, "minor")
assert(dm9.chord.notes.indexOf(76) !== -1, "Dm9 has E")

var caug = parseChord("Caug")
assert(caug.isValid, "parse Caug")
assertEq(caug.chord.quality, "augmented")
assertEq(caug.chord.notes.join(","), "60,64,68")

var cdim7 = parseChord("Cdim7")
assert(cdim7.isValid, "parse Cdim7")
assertEq(cdim7.chord.quality, "diminished")
assertEq(cdim7.chord.notes.join(","), "60,63,66,69")

assert(isValidChord("Dm9"))
assert(isValidChord("Csus4"))
assert(isValidChord("Csus2"))
assert(isValidChord("Caug"))
assert(isValidChord("Cdim7"))
assert(!isValidChord("Hmin"))
assert(!isValidChord("Cxyz"))
assert(getChordSuggestions("C").indexOf("C") !== -1)
assertEq(transposeChord("C", 7), "G")
assertEq(transposeChord("Am", 2), "Bm")

var song = defaultSong()
assertEq(song.sections.length, 2)
song = setChord(song, 0, 0, "C")
song = setChord(song, 0, 1, "G")
assertEq(song.sections[0].chords[0], "C")
var slots = flattenSlots(song)
assertEq(nextFilledSlot(slots, 0), 0)
assertEq(nextFilledSlot(slots, 1), 1)
song = addSection(song, "Bridge")
assertEq(song.sections.length, 3)
song = removeSection(song, 2)
assertEq(song.sections.length, 2)
var moved = transposeSong(song, 7, transposeChord)
assertEq(moved.sections[0].chords[0], "G")
var merged = mergeSong(song, { bpm: 96, loop: false })
assertEq(merged.bpm, 96)
assertEq(merged.loop, false)
assertEq(merged.sections[0].chords[0], "C")
assertEq(merged.title, song.title)

assertEq(midiForKey("a", 4, "qwerty"), 60, "a is C4")
assertEq(midiForKey("w", 4, "qwerty"), 61, "w is C#4")
var keys = twoOctaveKeys(4)
assertEq(keys.length, 24)
assertEq(keys[0].midi, 60)
assertEq(clampOctave(0), 1)
assertEq(computerKeyForMidi(60, 4, "qwerty"), "a")
