// Loaded into a VM with Model/Chords/Song/Keyboard functions in scope.

assertEq(PC_NAMES.join(" "), "C Db D Eb E F F# G Ab A Bb B")
assertEq(station(0).major, "C")
assertEq(station(0).relativeMinor, "Am")
assertEq(station(1).major, "G")
assertEq(station(11).major, "F")
assertEq(chordName(0, "major"), "C")
assertEq(chordName(0, "minor"), "Cm")
assertEq(chordName(0, "diminished"), "Cdim")
assertEq(chordName(0, "augmented"), "Caug")
assertEq(qualityInt("major"), 0)
assertEq(qualityInt("minor"), 1)
assertEq(qualityInt("diminished"), 2)
assertEq(qualityInt("augmented"), 3)
assertEq(encodeChord({ rootPc: 0, quality: "major" }), "chord|C|0|0")
assertEq(decodeChord("chord|Dm|2|1").rootPc, 2)
assertEq(decodeChord("chord|Dm|2|1").quality, "minor")
var dia = diatonicTriads(0)
assertEq(dia.length, 7)
assertEq(chordName(dia[0].rootPc, dia[0].quality), "C")
assertEq(chordName(dia[1].rootPc, dia[1].quality), "Dm")
assertEq(chordName(dia[6].rootPc, dia[6].quality), "Bdim")
assertEq(numeralFor(dia[0], 0), "I")
assertEq(maxSlots({ numerator: 4, denominator: 4 }), 4)
assertEq(maxSlots({ numerator: 3, denominator: 4 }), 3)
assertEq(maxSlots({ numerator: 2, denominator: 4 }), 2)
assertEq(maxSlots({ numerator: 6, denominator: 8 }), 6)
assertEq(beatsPerBar({ numerator: 4, denominator: 4 }), 4)
assertEq(beatsPerBar({ numerator: 6, denominator: 8 }), 3)
var midi = triadMidi({ rootPc: 0, quality: "major" })
assertEq(midi.length, 3)
assert(midi[0] >= 48 && midi[2] <= 72, "voiced in C3–C5")

// Polar / wedge helpers still used by CircleOfFifths.qml until Task 6.
assertEq(wrap(12), 0, "wrap 12")
assertEq(wrap(-1), 11, "wrap -1")
assertEq(keyAt(0).major, "C")
assertEq(keyAt(1).major, "G")
assertEq(label(0), "C / Am")
assert(inKeyWedge(0, 0), "tonic in wedge")
assert(inKeyWedge(1, 0), "dominant in wedge")
assert(inKeyWedge(11, 0), "subdominant in wedge")
assert(!inKeyWedge(2, 0), "D not in C wedge")
assertEq(triad(0, "major").label, "C")
assertEq(triad(0, "minor").label, "Am")
assertEq(triad(0, "major").notes.length, 3)

var c = parseChord("C")
assert(c.isValid, "parse C")
assertEq(c.chord.notes.join(","), "60,64,67")
assertEq(c.chord.quality, "major")

var cm = parseChord("Cm")
assert(cm.isValid, "parse Cm")
assertEq(cm.chord.quality, "minor")
assertEq(cm.chord.notes.join(","), "60,63,67")

var am = parseChord("Am")
assert(am.isValid, "parse Am")
assertEq(am.chord.quality, "minor")
assertEq(am.chord.notes.join(","), "69,72,76")

var c7 = parseChord("C7")
assert(c7.isValid, "parse C7")
assert(c7.chord.notes.indexOf(70) !== -1, "C7 has Bb")

var cmaj7 = parseChord("Cmaj7")
assert(cmaj7.isValid, "parse Cmaj7")
assertEq(cmaj7.chord.quality, "major")
assert(cmaj7.chord.notes.indexOf(71) !== -1, "Cmaj7 has B")
assertEq(cmaj7.chord.notes.join(","), "60,64,67,71")

var fdim = parseChord("F#dim")
assert(fdim.isValid, "parse F#dim")
assertEq(fdim.chord.quality, "diminished")
assertEq(fdim.chord.notes.join(","), "66,69,72")

var slash = parseChord("G/B")
assert(slash.isValid, "parse G/B")
assert(slash.chord.bass === "B" || slash.chord.bass === "b" || !!slash.chord.bass, "slash bass")

var csus4 = parseChord("Csus4")
assert(csus4.isValid, "parse Csus4")
assertEq(csus4.chord.quality, "sus4")
assertEq(csus4.chord.notes.join(","), "60,65,67")

var csus2 = parseChord("Csus2")
assert(csus2.isValid, "parse Csus2")
assertEq(csus2.chord.quality, "sus2")
assertEq(csus2.chord.notes.join(","), "60,62,67")

var dm9 = parseChord("Dm9")
assert(dm9.isValid, "parse Dm9")
assertEq(dm9.chord.quality, "minor")
assert(dm9.chord.notes.indexOf(76) !== -1, "Dm9 has E")

var caug = parseChord("Caug")
assert(caug.isValid, "parse Caug")
assertEq(caug.chord.quality, "augmented")
assertEq(caug.chord.notes.join(","), "60,64,68")

var cdim7 = parseChord("Cdim7")
assert(cdim7.isValid, "parse Cdim7")
assertEq(cdim7.chord.quality, "diminished")
assertEq(cdim7.chord.notes.join(","), "60,63,66,69")

assert(isValidChord("Dm9"))
assert(isValidChord("Csus4"))
assert(isValidChord("Csus2"))
assert(isValidChord("Caug"))
assert(isValidChord("Cdim7"))
assert(!isValidChord("Hmin"))
assert(!isValidChord("Cxyz"))
assert(getChordSuggestions("C").indexOf("C") !== -1)
assertEq(transposeChord("C", 7), "G")
assertEq(transposeChord("Am", 2), "Bm")

var song = defaultSong()
assertEq(song.bpm, 120)
assertEq(song.keyIndex, 0)
assertEq(song.sections.length, 2)
assertEq(song.sections[0].name, "Verse")
assertEq(song.sections[1].name, "Chorus")
assertEq(song.sections[0].timeSig.numerator, 4)
assertEq(song.sections[0].timeSig.denominator, 4)
assertEq(song.sections[0].measures.length, 4)
assertEq(song.sections[1].measures.length, 4)
assertEq(song.sections[0].measures[0].slots.length, 1)
assertEq(song.sections[0].measures[0].slots[0].span, 4)
assertEq(song.sections[0].rowRepeats.length, 1)
assertEq(song.sections[0].rowRepeats[0], false)
assertEq(chordName(song.sections[0].measures[0].slots[0].chord.rootPc, song.sections[0].measures[0].slots[0].chord.quality), "C")
assertEq(chordName(song.sections[0].measures[1].slots[0].chord.rootPc, song.sections[0].measures[1].slots[0].chord.quality), "G")
assertEq(chordName(song.sections[0].measures[2].slots[0].chord.rootPc, song.sections[0].measures[2].slots[0].chord.quality), "F")
assertEq(chordName(song.sections[0].measures[3].slots[0].chord.rootPc, song.sections[0].measures[3].slots[0].chord.quality), "Dm")
assertEq(chordName(song.sections[1].measures[0].slots[0].chord.rootPc, song.sections[1].measures[0].slots[0].chord.quality), "D")
assertEq(chordName(song.sections[1].measures[1].slots[0].chord.rootPc, song.sections[1].measures[1].slots[0].chord.quality), "G")
assertEq(chordName(song.sections[1].measures[2].slots[0].chord.rootPc, song.sections[1].measures[2].slots[0].chord.quality), "C")
assertEq(chordName(song.sections[1].measures[3].slots[0].chord.rootPc, song.sections[1].measures[3].slots[0].chord.quality), "Em")
assertEq(barsForTimeSignature({ numerator: 4, denominator: 4 }), 4)
assertEq(barsForTimeSignature({ numerator: 3, denominator: 4 }), 3)
assertEq(barsForTimeSignature({ numerator: 6, denominator: 8 }), 6)
assertEq(rowCount(4), 1)
assertEq(rowCount(6), 2)
assertEq(rowIndexForMeasure(3), 0)
assertEq(rowIndexForMeasure(4), 1)
assertEq(slotSpan(song, 0, 0, 0), 4)
assert(canSplitSlot(song, 0, 0, 0), "full chord can split")

// C++: removeSection is a no-op only for the last remaining section.
assertEq(removeSection(song, 0).sections.length, 1)
assertEq(removeSection(song, 0).sections[0].name, "Chorus")
assertEq(song.sections.length, 2)
assertEq(song.sections[0].name, "Verse")
var one = removeSection(removeSection(addSection(song, "Bridge"), 2), 1)
assertEq(one.sections.length, 1)
assertEq(one.sections[0].name, "Verse")
assertEq(removeSection(one, 0).sections.length, 1)
var bridge = addSection(song, "Bridge")
assertEq(bridge.sections.length, 3)
assertEq(bridge.sections[2].name, "Bridge")
assertEq(bridge.sections[2].measures.length, 4)
assertEq(bridge.sections[2].measures[0].slots[0].chord, null)
assertEq(bridge.sections[2].measures[0].slots[0].span, 4)
assertEq(addSection(song, "").sections[2].name, "Section")

var s3 = setTimeSignature(cloneSong(song), 0, { numerator: 3, denominator: 4 })
assertEq(s3.sections[0].measures.length, 3)
assertEq(slotSpanSum(s3.sections[0].measures[0]), 3)
assertEq(slotSpan(s3, 0, 0, 0), 3)
var s4sig = setTimeSignature(s3, 0, { numerator: 4, denominator: 4 })
assertEq(s4sig.sections[0].measures.length, 4)
assertEq(s4sig.sections[0].rowRepeats.length, 1)
var six = setTimeSignature(cloneSong(song), 0, { numerator: 6, denominator: 8 })
assertEq(six.sections[0].measures.length, 6)
assertEq(six.sections[0].rowRepeats.length, 2)
assertEq(slotSpanSum(six.sections[0].measures[0]), 6)

var placed = placeChord(cloneSong(song), 0, 0, 0, { rootPc: 7, quality: "major" }, false)
assert(placed.sections[0].measures[0].slots[0].chord.rootPc === 7)
var split = placeChord(cloneSong(song), 0, 0, 0, { rootPc: 7, quality: "major" }, true)
assert(split.sections[0].measures[0].slots.length >= 2)
assertEq(slotSpanSum(split.sections[0].measures[0]), 4)
var resized = resizeSlot(cloneSong(song), 0, 0, 0, 2, "right")
assertEq(slotSpanSum(resized.sections[0].measures[0]), 4)
var cleared = setChord(cloneSong(song), 0, 0, 0, null)
assertEq(cleared.sections[0].measures[0].slots[0].chord, null)

// C++ SongModelTest placeChord edges: split, insert side, max-capacity replace.
var sPlace = cloneSong(song)
sPlace = placeChord(sPlace, 0, 0, 0, { rootPc: 5, quality: "major" }, true)
assertEq(sPlace.sections[0].measures[0].slots.length, 2)
assertEq(chordName(sPlace.sections[0].measures[0].slots[0].chord.rootPc, sPlace.sections[0].measures[0].slots[0].chord.quality), "C")
assertEq(chordName(sPlace.sections[0].measures[0].slots[1].chord.rootPc, sPlace.sections[0].measures[0].slots[1].chord.quality), "F")
assertEq(slotSpan(sPlace, 0, 0, 0), 2)
assertEq(slotSpan(sPlace, 0, 0, 1), 2)
sPlace = placeChord(sPlace, 0, 0, 0, { rootPc: 7, quality: "major" }, false)
assertEq(sPlace.sections[0].measures[0].slots.length, 3)
assertEq(chordName(sPlace.sections[0].measures[0].slots[0].chord.rootPc, sPlace.sections[0].measures[0].slots[0].chord.quality), "G")
assertEq(slotSpan(sPlace, 0, 0, 0), 1)
assertEq(slotSpan(sPlace, 0, 0, 1), 1)
assertEq(slotSpan(sPlace, 0, 0, 2), 2)
sPlace = placeChord(sPlace, 0, 0, 2, { rootPc: 2, quality: "minor" }, true)
assertEq(sPlace.sections[0].measures[0].slots.length, 4)
sPlace = placeChord(sPlace, 0, 0, 0, { rootPc: 2, quality: "major" }, true)
assertEq(sPlace.sections[0].measures[0].slots.length, 4)
assertEq(chordName(sPlace.sections[0].measures[0].slots[0].chord.rootPc, sPlace.sections[0].measures[0].slots[0].chord.quality), "D")

var emptyBar = setChord(cloneSong(song), 0, 0, 0, null)
var filledEmpty = placeChord(emptyBar, 0, 0, 0, { rootPc: 0, quality: "major" }, true)
assertEq(filledEmpty.sections[0].measures[0].slots.length, 1)
assertEq(filledEmpty.sections[0].measures[0].slots[0].chord.rootPc, 0)

// C++ resizeSlot: shrink opens unit empties; grow absorbs them.
var sResize = resizeSlot(cloneSong(song), 0, 0, 0, 2, "right")
assertEq(sResize.sections[0].measures[0].slots.length, 3)
assertEq(chordName(sResize.sections[0].measures[0].slots[0].chord.rootPc, sResize.sections[0].measures[0].slots[0].chord.quality), "C")
assertEq(slotSpan(sResize, 0, 0, 0), 2)
assertEq(sResize.sections[0].measures[0].slots[1].chord, null)
assertEq(sResize.sections[0].measures[0].slots[2].chord, null)
assertEq(slotSpan(sResize, 0, 0, 1), 1)
assertEq(slotSpan(sResize, 0, 0, 2), 1)
sResize = resizeSlot(sResize, 0, 0, 0, 1, "right")
assertEq(sResize.sections[0].measures[0].slots.length, 4)
assertEq(emptySpanOnSide(sResize, 0, 0, 0, false), 3)
sResize = resizeSlot(sResize, 0, 0, 0, 3, "right")
assertEq(sResize.sections[0].measures[0].slots.length, 2)
assertEq(slotSpan(sResize, 0, 0, 0), 3)
assertEq(sResize.sections[0].measures[0].slots[1].chord, null)

var sLeft = resizeSlot(cloneSong(song), 0, 0, 0, 2, "left")
assertEq(sLeft.sections[0].measures[0].slots.length, 3)
assertEq(sLeft.sections[0].measures[0].slots[0].chord, null)
assertEq(sLeft.sections[0].measures[0].slots[1].chord, null)
assertEq(chordName(sLeft.sections[0].measures[0].slots[2].chord.rootPc, sLeft.sections[0].measures[0].slots[2].chord.quality), "C")

var sMeter = setTimeSignature(cloneSong(song), 0, { numerator: 3, denominator: 4 })
sMeter = resizeSlot(sMeter, 0, 0, 0, 1, "right")
assertEq(sMeter.sections[0].measures[0].slots.length, 3)
sMeter = addSlot(sMeter, 0, 0)
assertEq(sMeter.sections[0].measures[0].slots.length, 3)

assertEq(setBpm(cloneSong(song), 96).bpm, 96)
assertEq(setBpm(cloneSong(song), 10).bpm, 40)
assertEq(setBpm(cloneSong(song), 300).bpm, 240)

var splitBefore = song.sections[0].measures[1].slots.length
var added = addSlot(cloneSong(song), 0, 1)
assertEq(added.sections[0].measures[1].slots.length, splitBefore + 1)

assertEq(semitoneForKey("a"), 0)
assertEq(semitoneForKey("w"), 1)
assertEq(semitoneForKey("s"), 2)
assertEq(semitoneForKey("j"), 11)
assertEq(semitoneForKey("k"), 12)
assertEq(semitoneForKey("z"), -1)
assertEq(midiForLaptopKey("a", 4), 60)
assertEq(midiForLaptopKey("w", 4), 61)
assertEq(midiForLaptopKey("k", 4), 72)
assertEq(shiftOctave(4, 1), 5)
assertEq(shiftOctave(8, 1), 8)
assertEq(shiftOctave(0, -1), 0)
assertEq(clampMidi(midiForLaptopKey("a", 0)), midiForLaptopKey("a", 0))
