// Loaded into a VM with Model/Song/Agent/Keyboard/Focus functions in scope.

assertEq(PC_NAMES.join(" "), "C Db D Eb E F F# G Ab A Bb B")
assertEq(station(0).major, "C")
assertEq(station(0).relativeMinor, "Am")
assertEq(station(1).major, "G")
assertEq(station(11).major, "F")
assertEq(chordName(0, "major"), "C")
assertEq(chordName(0, "minor"), "Cm")
assertEq(chordName(0, "diminished"), "Cdim")
assertEq(chordName(0, "augmented"), "Caug")
assertEq(qualityInt("major"), 0)
assertEq(qualityInt("minor"), 1)
assertEq(qualityInt("diminished"), 2)
assertEq(qualityInt("augmented"), 3)
assertEq(encodeChord({ rootPc: 0, quality: "major" }), "chord|C|0|0")
assertEq(decodeChord("chord|Dm|2|1").rootPc, 2)
assertEq(decodeChord("chord|Dm|2|1").quality, "minor")
var dia = diatonicTriads(0)
assertEq(dia.length, 7)
assertEq(chordName(dia[0].rootPc, dia[0].quality), "C")
assertEq(chordName(dia[1].rootPc, dia[1].quality), "Dm")
assertEq(chordName(dia[6].rootPc, dia[6].quality), "Bdim")
assertEq(numeralFor(dia[0], 0), "I")
assertEq(maxSlots({ numerator: 4, denominator: 4 }), 4)
assertEq(maxSlots({ numerator: 3, denominator: 4 }), 3)
assertEq(maxSlots({ numerator: 2, denominator: 4 }), 2)
assertEq(maxSlots({ numerator: 6, denominator: 8 }), 6)
assertEq(beatsPerBar({ numerator: 4, denominator: 4 }), 4)
assertEq(beatsPerBar({ numerator: 6, denominator: 8 }), 3)
var midi = triadMidi({ rootPc: 0, quality: "major" })
assertEq(midi.length, 3)
assert(midi[0] >= 48 && midi[2] <= 72, "voiced in C3–C5")

// Polar / wedge helpers used by CircleOfFifths.qml (rotated key at 12 o'clock).
assertEq(wrap(12), 0, "wrap 12")
assertEq(wrap(-1), 11, "wrap -1")
assertEq(wrap(0 + 1), 1)
assertEq(wrap(0 - 1), 11)
assertEq(rotate(0, 1), 1)
assertEq(rotate(0, -1), 11)
assertEq(rotate(11, 1), 0)
assertEq(rotate(1, -1), 0)
assertEq(visualSector(0, 0), 0)
assertEq(visualSector(1, 1), 0)
assertEq(visualSector(0, 1), 11)
var hitTopC = hitTest(100, 10, 100, 100, 20, 40, 50, 95, 0)
assertEq(hitTopC.ring, "major")
assertEq(hitTopC.index, 0)
var hitTopG = hitTest(100, 10, 100, 100, 20, 40, 50, 95, 1)
assertEq(hitTopG.index, 1)
assertEq(keyAt(0).major, "C")
assertEq(keyAt(1).major, "G")
assertEq(label(0), "C / Am")
assert(inKeyWedge(0, 0), "tonic in wedge")
assert(inKeyWedge(1, 0), "dominant in wedge")
assert(inKeyWedge(11, 0), "subdominant in wedge")
assert(!inKeyWedge(2, 0), "D not in C wedge")
assertEq(triad(0, "major").label, "C")
assertEq(triad(0, "minor").label, "Am")
assertEq(triad(0, "major").notes.length, 3)
var selectedC = { rootPc: 0, quality: "major" }
var previewG = { rootPc: 7, quality: "major" }
var playF = { rootPc: 5, quality: "major" }
assertEq(resolveDisplayChord(false, null, null, selectedC).rootPc, 0)
assertEq(resolveDisplayChord(false, null, previewG, selectedC).rootPc, 7, "circle preview sticks over selected slot")
assertEq(resolveDisplayChord(false, null, previewG, selectedC).rootPc, 7, "preview still wins after audition notes clear")
assertEq(resolveDisplayChord(true, playF, previewG, selectedC).rootPc, 5)
assertEq(resolveDisplayChord(false, playF, previewG, selectedC).rootPc, 7, "after stop, circle preview remains")
assertEq(resolveDisplayChord(false, null, null, null), null)
assertEq(triad(0, "major").rootPc, 0)
assertEq(triad(0, "major").quality, "major")
assertEq(triad(0, "minor").rootPc, 9)
assertEq(triad(0, "minor").quality, "minor")

var song = defaultSong()
assertEq(song.bpm, 120)
assertEq(song.keyIndex, 0)
assertEq(song.sections.length, 2)
assertEq(song.sections[0].name, "Verse")
assertEq(song.sections[1].name, "Chorus")
assertEq(song.sections[0].timeSig.numerator, 4)
assertEq(song.sections[0].timeSig.denominator, 4)
assertEq(song.sections[0].measures.length, 4)
assertEq(song.sections[1].measures.length, 4)
assertEq(song.sections[0].measures[0].slots.length, 1)
assertEq(song.sections[0].measures[0].slots[0].span, 4)
assertEq(song.sections[0].rowRepeats.length, 1)
assertEq(song.sections[0].rowRepeats[0], false)
assertEq(chordName(song.sections[0].measures[0].slots[0].chord.rootPc, song.sections[0].measures[0].slots[0].chord.quality), "C")
assertEq(chordName(song.sections[0].measures[1].slots[0].chord.rootPc, song.sections[0].measures[1].slots[0].chord.quality), "G")
assertEq(chordName(song.sections[0].measures[2].slots[0].chord.rootPc, song.sections[0].measures[2].slots[0].chord.quality), "F")
assertEq(chordName(song.sections[0].measures[3].slots[0].chord.rootPc, song.sections[0].measures[3].slots[0].chord.quality), "Dm")
assertEq(chordName(song.sections[1].measures[0].slots[0].chord.rootPc, song.sections[1].measures[0].slots[0].chord.quality), "D")
assertEq(chordName(song.sections[1].measures[1].slots[0].chord.rootPc, song.sections[1].measures[1].slots[0].chord.quality), "G")
assertEq(chordName(song.sections[1].measures[2].slots[0].chord.rootPc, song.sections[1].measures[2].slots[0].chord.quality), "C")
assertEq(chordName(song.sections[1].measures[3].slots[0].chord.rootPc, song.sections[1].measures[3].slots[0].chord.quality), "Em")
assertEq(rowCount(4), 1)
assertEq(rowCount(6), 2)
assertEq(rowIndexForMeasure(3), 0)
assertEq(rowIndexForMeasure(4), 1)
assertEq(slotSpan(song, 0, 0, 0), 4)
assert(canSplitSlot(song, 0, 0, 0), "full chord can split")

// removeSection is a no-op only for the last remaining section.
assertEq(removeSection(song, 0).sections.length, 1)
assertEq(removeSection(song, 0).sections[0].name, "Chorus")
assertEq(song.sections.length, 2)
assertEq(song.sections[0].name, "Verse")
var one = removeSection(removeSection(addSection(song, "Bridge"), 2), 1)
assertEq(one.sections.length, 1)
assertEq(one.sections[0].name, "Verse")
assertEq(removeSection(one, 0).sections.length, 1)
var bridge = addSection(song, "Bridge")
assertEq(bridge.sections.length, 3)
assertEq(bridge.sections[2].name, "Bridge")
assertEq(bridge.sections[2].measures.length, 4)
assertEq(bridge.sections[2].measures[0].slots[0].chord, null)
assertEq(bridge.sections[2].measures[0].slots[0].span, 4)
assertEq(addSection(song, "").sections[2].name, "Section")
var capped = song
for (var si = 0; si < 40; si++)
  capped = addSection(capped, "S" + si)
assertEq(capped.sections.length, MAX_SECTIONS)
var hugeBars = addBars(cloneSong(song), 0, 500)
assert(hugeBars.sections[0].measures.length <= MAX_MEASURES_PER_SECTION)
var hugeSig = setTimeSignature(cloneSong(song), 0, { numerator: 99, denominator: 4 })
assertEq(hugeSig.sections[0].timeSig.numerator, MAX_TIME_NUMERATOR)

var s3 = setTimeSignature(cloneSong(song), 0, { numerator: 3, denominator: 4 })
assertEq(s3.sections[0].measures.length, 4)
assertEq(slotSpanSum(s3.sections[0].measures[0]), 3)
assertEq(slotSpan(s3, 0, 0, 0), 3)
var s4sig = setTimeSignature(s3, 0, { numerator: 4, denominator: 4 })
assertEq(s4sig.sections[0].measures.length, 4)
assertEq(s4sig.sections[0].rowRepeats.length, 1)
var six = setTimeSignature(cloneSong(song), 0, { numerator: 6, denominator: 8 })
assertEq(six.sections[0].measures.length, 4)
assertEq(six.sections[0].rowRepeats.length, 1)
assertEq(slotSpanSum(six.sections[0].measures[0]), 6)

var eight = addBars(cloneSong(song), 0)
assertEq(eight.sections[0].measures.length, 8)
assertEq(eight.sections[0].rowRepeats.length, 2)
assertEq(eight.sections[0].measures[7].slots[0].chord, null)
assertEq(removeMeasure(eight, 0, 7).sections[0].measures.length, 7)
assertEq(removeMeasure(eight, 0, 0).sections[0].measures.length, 8)
var trimmed = removeMeasure(removeMeasure(removeMeasure(removeMeasure(eight, 0, 7), 0, 6), 0, 5), 0, 4)
assertEq(trimmed.sections[0].measures.length, 4)
assertEq(removeMeasure(trimmed, 0, 3).sections[0].measures.length, 4)

var placed = placeChord(cloneSong(song), 0, 0, 0, { rootPc: 7, quality: "major" }, false)
assert(placed.sections[0].measures[0].slots[0].chord.rootPc === 7)
var split = placeChord(cloneSong(song), 0, 0, 0, { rootPc: 7, quality: "major" }, true)
assert(split.sections[0].measures[0].slots.length >= 2)
assertEq(slotSpanSum(split.sections[0].measures[0]), 4)
var resized = resizeSlot(cloneSong(song), 0, 0, 0, 2, "right")
assertEq(slotSpanSum(resized.sections[0].measures[0]), 4)
var cleared = setChord(cloneSong(song), 0, 0, 0, null)
assertEq(cleared.sections[0].measures[0].slots[0].chord, null)

// placeChord edges: split, insert side, max-capacity replace.
var sPlace = cloneSong(song)
sPlace = placeChord(sPlace, 0, 0, 0, { rootPc: 5, quality: "major" }, true)
assertEq(sPlace.sections[0].measures[0].slots.length, 2)
assertEq(chordName(sPlace.sections[0].measures[0].slots[0].chord.rootPc, sPlace.sections[0].measures[0].slots[0].chord.quality), "C")
assertEq(chordName(sPlace.sections[0].measures[0].slots[1].chord.rootPc, sPlace.sections[0].measures[0].slots[1].chord.quality), "F")
assertEq(slotSpan(sPlace, 0, 0, 0), 2)
assertEq(slotSpan(sPlace, 0, 0, 1), 2)
sPlace = placeChord(sPlace, 0, 0, 0, { rootPc: 7, quality: "major" }, false)
assertEq(sPlace.sections[0].measures[0].slots.length, 3)
assertEq(chordName(sPlace.sections[0].measures[0].slots[0].chord.rootPc, sPlace.sections[0].measures[0].slots[0].chord.quality), "G")
assertEq(slotSpan(sPlace, 0, 0, 0), 1)
assertEq(slotSpan(sPlace, 0, 0, 1), 1)
assertEq(slotSpan(sPlace, 0, 0, 2), 2)
sPlace = placeChord(sPlace, 0, 0, 2, { rootPc: 2, quality: "minor" }, true)
assertEq(sPlace.sections[0].measures[0].slots.length, 4)
sPlace = placeChord(sPlace, 0, 0, 0, { rootPc: 2, quality: "major" }, true)
assertEq(sPlace.sections[0].measures[0].slots.length, 4)
assertEq(chordName(sPlace.sections[0].measures[0].slots[0].chord.rootPc, sPlace.sections[0].measures[0].slots[0].chord.quality), "D")

var emptyBar = setChord(cloneSong(song), 0, 0, 0, null)
var filledEmpty = placeChord(emptyBar, 0, 0, 0, { rootPc: 0, quality: "major" }, true)
assertEq(filledEmpty.sections[0].measures[0].slots.length, 1)
assertEq(filledEmpty.sections[0].measures[0].slots[0].chord.rootPc, 0)

// moveChord: drag a placed chord to either side of another.
var splitBar = placeChord(cloneSong(song), 0, 0, 0, { rootPc: 5, quality: "major" }, true)
assertEq(chordName(splitBar.sections[0].measures[0].slots[0].chord.rootPc, splitBar.sections[0].measures[0].slots[0].chord.quality), "C")
assertEq(chordName(splitBar.sections[0].measures[0].slots[1].chord.rootPc, splitBar.sections[0].measures[0].slots[1].chord.quality), "F")
var movedBefore = moveChord(splitBar, 0, 0, 1, 0, 0, 0, false)
assertEq(chordName(movedBefore.sections[0].measures[0].slots[0].chord.rootPc, movedBefore.sections[0].measures[0].slots[0].chord.quality), "F")
assertEq(chordName(movedBefore.sections[0].measures[0].slots[1].chord.rootPc, movedBefore.sections[0].measures[0].slots[1].chord.quality), "C")
var movedAfter = moveChord(splitBar, 0, 0, 0, 0, 0, 1, true)
assertEq(chordName(movedAfter.sections[0].measures[0].slots[0].chord.rootPc, movedAfter.sections[0].measures[0].slots[0].chord.quality), "F")
assertEq(chordName(movedAfter.sections[0].measures[0].slots[1].chord.rootPc, movedAfter.sections[0].measures[0].slots[1].chord.quality), "C")
var crossBar = moveChord(cloneSong(song), 0, 0, 0, 0, 1, 0, false)
assertEq(crossBar.sections[0].measures[0].slots[0].chord, null)
assertEq(chordName(crossBar.sections[0].measures[1].slots[0].chord.rootPc, crossBar.sections[0].measures[1].slots[0].chord.quality), "C")
assertEq(chordName(crossBar.sections[0].measures[1].slots[1].chord.rootPc, crossBar.sections[0].measures[1].slots[1].chord.quality), "G")
assertEq(moveChord(song, 0, 0, 0, 0, 0, 0, true).sections[0].measures[0].slots[0].chord.rootPc, 0)

// resizeSlot: shrink opens unit empties; grow absorbs them.
var sResize = resizeSlot(cloneSong(song), 0, 0, 0, 2, "right")
assertEq(sResize.sections[0].measures[0].slots.length, 3)
assertEq(chordName(sResize.sections[0].measures[0].slots[0].chord.rootPc, sResize.sections[0].measures[0].slots[0].chord.quality), "C")
assertEq(slotSpan(sResize, 0, 0, 0), 2)
assertEq(sResize.sections[0].measures[0].slots[1].chord, null)
assertEq(sResize.sections[0].measures[0].slots[2].chord, null)
assertEq(slotSpan(sResize, 0, 0, 1), 1)
assertEq(slotSpan(sResize, 0, 0, 2), 1)
sResize = resizeSlot(sResize, 0, 0, 0, 1, "right")
assertEq(sResize.sections[0].measures[0].slots.length, 4)
assertEq(emptySpanOnSide(sResize, 0, 0, 0, false), 3)
sResize = resizeSlot(sResize, 0, 0, 0, 3, "right")
assertEq(sResize.sections[0].measures[0].slots.length, 2)
assertEq(slotSpan(sResize, 0, 0, 0), 3)
assertEq(sResize.sections[0].measures[0].slots[1].chord, null)

var sLeft = resizeSlot(cloneSong(song), 0, 0, 0, 2, "left")
assertEq(sLeft.sections[0].measures[0].slots.length, 3)
assertEq(sLeft.sections[0].measures[0].slots[0].chord, null)
assertEq(sLeft.sections[0].measures[0].slots[1].chord, null)
assertEq(chordName(sLeft.sections[0].measures[0].slots[2].chord.rootPc, sLeft.sections[0].measures[0].slots[2].chord.quality), "C")

var sMeter = setTimeSignature(cloneSong(song), 0, { numerator: 3, denominator: 4 })
sMeter = resizeSlot(sMeter, 0, 0, 0, 1, "right")
assertEq(sMeter.sections[0].measures[0].slots.length, 3)
sMeter = addSlot(sMeter, 0, 0)
assertEq(sMeter.sections[0].measures[0].slots.length, 3)

assertEq(setBpm(cloneSong(song), 96).bpm, 96)
assertEq(setBpm(cloneSong(song), 10).bpm, 40)
assertEq(setBpm(cloneSong(song), 300).bpm, 240)

var splitBefore = song.sections[0].measures[1].slots.length
var added = addSlot(cloneSong(song), 0, 1)
assertEq(added.sections[0].measures[1].slots.length, splitBefore + 1)

assertEq(semitoneForKey("a"), 0)
assertEq(semitoneForKey("w"), 1)
assertEq(semitoneForKey("s"), 2)
assertEq(semitoneForKey("j"), 11)
assertEq(semitoneForKey("k"), 12)
assertEq(semitoneForKey("z"), -1)
assertEq(midiForLaptopKey("a", 4), 60)
assertEq(midiForLaptopKey("w", 4), 61)
assertEq(midiForLaptopKey("k", 4), 72)
var keys = pianoKeysC3C5()
assertEq(keys[0].midi, 48)
assertEq(keys[keys.length - 1].midi, 72)
assertEq(wrapInstrument(-1), 4)
assertEq(wrapInstrument(5), 0)
assertEq(instrumentName(1), "Electric Piano")
assertEq(shiftOctave(4, 1), 5)
assertEq(shiftOctave(8, 1), 8)
assertEq(shiftOctave(0, -1), 0)
assertEq(clampMidi(midiForLaptopKey("a", 0)), midiForLaptopKey("a", 0))

var song = defaultSong()
var tl = buildTimeline(song)
assertEq(tl.length, 8)
assertEq(tl[0].durationBeats, 4)
assertEq(tl[0].rest, false)
assertEq(beatsToSeconds(4, 120), 2)
assertEq(beatsToSeconds(1, 60), 1)
assertEq(timelineDurationBeats(tl), 32)
var verseTl = buildSectionTimeline(song, 0)
assertEq(verseTl.length, 4)
assertEq(timelineDurationBeats(verseTl), 16)
assertEq(verseTl[0].sectionIndex, 0)
assertEq(verseTl[verseTl.length - 1].sectionIndex, 0)
var chorusTl = buildSectionTimeline(song, 1)
assertEq(chorusTl.length, 4)
assertEq(timelineDurationBeats(chorusTl), 16)
assertEq(chorusTl[0].sectionIndex, 1)
assertEq(buildSectionTimeline(song, -1).length, 0)
assertEq(buildSectionTimeline(song, 99).length, 0)
assertEq(eventAtBeat(tl, 0).measureIndex, 0)
assertEq(eventAtBeat(tl, 4).measureIndex, 1)
assertEq(eventAtBeat(tl, 31).sectionIndex, 1)
var beats = 0
for (var i = 0; i < tl.length; i++) beats += tl[i].durationBeats
assertEq(beats, 32)
var restTl = buildTimeline(setChord(cloneSong(song), 0, 0, 0, null))
assertEq(restTl[0].rest, true)
assertEq(restTl[0].durationBeats, 4)
var walked = 0
var lastStart = -1
for (var b = 0; b < timelineDurationBeats(tl); b++) {
  var ev = eventAtBeat(tl, b)
  assert(ev, "event at beat " + b)
  if (ev.startBeat !== lastStart) {
    walked++
    lastStart = ev.startBeat
  }
}
assertEq(walked, 8)
assertEq(eventAtBeat(tl, timelineDurationBeats(tl)), null)
var repeated = setRowRepeat(cloneSong(song), 0, 0, true)
var tl2 = buildTimeline(repeated)
assertEq(tl2.length, 12)
beats = 0
for (i = 0; i < tl2.length; i++) beats += tl2[i].durationBeats
assertEq(beats, 48)
assertEq(tl2[4].repeatPass, 1)
var six = setTimeSignature(cloneSong(song), 0, { numerator: 6, denominator: 8 })
assertEq(six.sections[0].rowRepeats.length, 1)
assertEq(slotDurationBeats(4, 4), 4)
assertEq(slotDurationBeats(2, 4), 2)
assertEq(slotDurationBeats(1, 4), 1)
assertEq(slotDurationBeats(3, 4), 3)
assertEq(slotDurationBeats(4, 0), 4)
assertEq(slotDurationBeats(4, -1), 4)
assertEq(slotDurationBeatsAt(song, 0, 0, 0), 4)
var splitDur = resizeSlot(cloneSong(song), 0, 0, 0, 2, "right")
assertEq(slotDurationBeatsAt(splitDur, 0, 0, 0), 2)
assertEq(slotDurationBeatsAt(splitDur, 0, 0, 1), 1)
var threeFour = setTimeSignature(cloneSong(song), 0, { numerator: 3, denominator: 4 })
assertEq(slotDurationBeatsAt(threeFour, 0, 0, 0), 3)
assertEq(slotDurationBeatsAt(song, -1, 0, 0), 0)
assertEq(slotDurationBeatsAt(song, 0, 99, 0), 0)
assertEq(slotDurationBeatsAt(song, 0, 0, 99), 0)
assertEq(beatsToSeconds(4, 120), 2)
assertEq(beatsToSeconds(2, 120), 1)
assertEq(slotDurationBeats(6, 8), 3)
assertEq(slotDurationBeats(1, 8), 0.5)
assertEq(six.sections[0].measures[0].slots[0].span, 6)
assertEq(buildTimeline(six)[0].durationBeats, 3)
var sixSplit = resizeSlot(cloneSong(six), 0, 0, 0, 1, "right")
assertEq(sixSplit.sections[0].measures[0].slots[0].span, 1)
var sixTl = buildTimeline(sixSplit)
assertEq(sixTl[0].durationBeats, 0.5)
assertEq(sixTl[1].startBeat, 0.5)
var walkBeat = 0
var walkHits = 0
while (walkBeat < timelineDurationBeats(sixTl)) {
  var walkEv = eventAtBeat(sixTl, walkBeat)
  assert(walkEv, "eventAtBeat at " + walkBeat)
  assertEq(walkEv.startBeat, sixTl[walkHits].startBeat)
  walkHits++
  walkBeat = walkEv.startBeat + walkEv.durationBeats
}
assertEq(walkHits, sixTl.length)
for (var ei = 0; ei < sixTl.length; ei++) {
  var atStart = eventAtBeat(sixTl, sixTl[ei].startBeat)
  assertEq(atStart.startBeat, sixTl[ei].startBeat)
  assertEq(atStart.slotIndex, sixTl[ei].slotIndex)
}
assertEq(eventAtBeat(sixTl, 0.5).startBeat, 0.5)
assertEq(beatTickDelta(tl, 0), 1)
assertEq(beatTickDelta(tl, 3), 1)
assertEq(beatTickDelta(sixTl, 0), 0.5)
assertEq(beatTickDelta(sixTl, 0.5), 0.5)
var clockDisplay = []
var clockBeat = 0
while (clockBeat < 4) {
  clockDisplay.push(Math.floor(clockBeat) + 1)
  clockBeat += beatTickDelta(tl, clockBeat)
}
assertEq(clockDisplay.join(","), "1,2,3,4")
var clockHits = {}
clockBeat = 0
while (clockBeat < timelineDurationBeats(sixTl)) {
  clockHits[String(eventAtBeat(sixTl, clockBeat).startBeat)] = true
  clockBeat += beatTickDelta(sixTl, clockBeat)
}
assert(clockHits["0.5"], "beat clock hits 0.5")
assertEq(beatTickDelta([{ startBeat: 0, durationBeats: 4 }], 0), 1)
assertEq(beatTickDelta([{ startBeat: 0.5, durationBeats: 1.5 }], 0.5), 0.5)
assertEq(beatTickDelta([{ startBeat: 0.5, durationBeats: 0.5 }], 0.5), 0.5)
var sixTwo = resizeSlot(cloneSong(six), 0, 0, 0, 3, "right")
sixTwo = resizeSlot(sixTwo, 0, 0, 1, 3, "right")
assertEq(sixTwo.sections[0].measures[0].slots.length, 2)
assertEq(sixTwo.sections[0].measures[0].slots[0].span, 3)
assertEq(sixTwo.sections[0].measures[0].slots[1].span, 3)
var twoTl = buildTimeline(sixTwo)
assertEq(twoTl[0].durationBeats, 1.5)
assertEq(twoTl[1].startBeat, 1.5)
assertEq(twoTl[1].durationBeats, 1.5)
var twoClock = []
var twoBeat = 0
while (twoBeat < 3) {
  twoClock.push(twoBeat)
  twoBeat += beatTickDelta(twoTl, twoBeat)
}
twoClock.push(twoBeat)
assertEq(twoClock.join(","), "0,1,1.5,2,3")

// Agent JSON (progressions omit empties; song includes every slot).
var song = defaultSong()
song.keyIndex = 0
var p = progressionsJson(song)
assertEq(p.key.major, "C")
assertEq(p.bpm, 120)
assert(p.sections[0].progression.indexOf("C") !== -1)
assertEq(p.sections[0].chords[0].numeral, "I")
var doc = songJson(song)
assertEq(doc.sections[0].measures[0].slots[0].rootPc, 0)
assertEq(songJson(setChord(cloneSong(song), 0, 0, 0, null)).sections[0].measures[0].slots[0], null)

// Progressions and song JSON shapes.
assertEq(p.key.index, 0)
assertEq(p.key.relativeMinor, "Am")
assertEq(p.sections[0].name, "Verse")
assertEq(p.sections[0].timeSignature, "4/4")
assertEq(p.sections[0].rowRepeats.length, 1)
assertEq(p.sections[0].rowRepeats[0], false)
assertEq(p.sections[0].progression, "C | G | F | Dm")
assertEq(p.sections[1].progression, "D | G | C | Em")
assertEq(p.sections[0].chords.length, 4)
assertEq(p.sections[0].chords[0].name, "C")
assertEq(p.sections[0].chords[0].root, "C")
assertEq(p.sections[0].chords[0].rootPc, 0)
assertEq(p.sections[0].chords[0].quality, "major")
assertEq(p.sections[0].chords[0].bar, 0)
assertEq(p.sections[0].chords[0].slot, 0)
assertEq(p.sections[0].chords[3].name, "Dm")
assertEq(p.sections[0].chords[3].numeral, "ii")
assertEq(p.sections[1].chords[0].name, "D")
assertEq(p.sections[1].chords[0].numeral, undefined)
assertEq(p.sections[1].chords[3].numeral, "iii")
assertEq(doc.sections[0].measures[0].slots[0].name, "C")
assertEq(doc.sections[0].measures[0].slots[0].numeral, "I")
assertEq(doc.sections[0].measures[0].slots[0].bar, undefined)
assertEq(doc.sections[0].measures[0].slots[0].slot, undefined)
assertEq(doc.sections[0].rowRepeats[0], false)

var clearedProg = progressionsJson(setChord(cloneSong(song), 0, 0, 0, null))
assertEq(clearedProg.sections[0].progression, "- | G | F | Dm")
assertEq(clearedProg.sections[0].chords.length, 3)
assertEq(clearedProg.sections[0].chords[0].name, "G")
assertEq(clearedProg.sections[0].chords[0].bar, 1)

var mixed = placeChord(cloneSong(song), 0, 1, 0, { rootPc: 5, quality: "major" }, true)
mixed = placeChord(mixed, 0, 1, 1, { rootPc: 0, quality: "major" }, true)
var pMixed = progressionsJson(mixed)
assertEq(pMixed.sections[0].progression, "C | G F C | F | Dm")
assertEq(pMixed.sections[0].chords[3].name, "C")
assertEq(pMixed.sections[0].chords[3].bar, 1)
assertEq(pMixed.sections[0].chords[3].slot, 2)

var repeated = setRowRepeat(cloneSong(song), 0, 0, true)
assertEq(progressionsJson(repeated).sections[0].rowRepeats[0], true)
var sixDoc = songJson(setTimeSignature(cloneSong(song), 0, { numerator: 6, denominator: 8 }))
assertEq(sixDoc.sections[0].timeSignature, "6/8")
assertEq(sixDoc.sections[0].rowRepeats.length, 1)

assertEq(progressionsJson({}).bpm, 120)
assertEq(songJson({}).bpm, 120)
var wrappedPc = cloneSong(song)
wrappedPc.sections[0].measures[0].slots[0].chord = { rootPc: 12, quality: "major" }
assertEq(progressionsJson(wrappedPc).sections[0].chords[0].numeral, "I")
assertEq(progressionsJson(wrappedPc).sections[0].chords[0].rootPc, 0)
var savedNumeralFor = numeralFor
numeralFor = function () { return "" }
assertEq(progressionsJson(defaultSong()).sections[0].chords[0].numeral, "I")
numeralFor = savedNumeralFor

// Region focus cycle (j down, k up, wrap).
assertEq(cycleNavRegion(0, 1), 1)
assertEq(cycleNavRegion(2, 1), 0)
assertEq(cycleNavRegion(0, -1), 2)
assertEq(regionName(0), "Circle of fifths")
assertEq(regionName(1), "Song structure")
assertEq(regionName(2), "Keyboard")
assertEq(degreeIndexFromKey(0x31, "1"), 0)
assertEq(degreeIndexFromKey(0x37, "7"), 6)
assertEq(degreeIndexFromKey(0x01000033, "3"), 2)
assertEq(degreeIndexFromKey(0x48, "h"), -1)

// Guitar tab voicings (standard tuning, low E → high e).
function assertFrets(rootPc, quality, expected, label) {
  var v = voicingFor(rootPc, quality)
  assertEq(v.frets.join(","), expected.join(","), label)
  assert(coversChord(v.frets, rootPc, quality), label + " covers triad")
}
assertFrets(0, "major", [-1, 3, 2, 0, 1, 0], "C")
assertFrets(7, "major", [3, 2, 0, 0, 0, 3], "G")
assertFrets(5, "major", [1, 3, 3, 2, 1, 1], "F")
assertFrets(2, "major", [-1, -1, 0, 2, 3, 2], "D")
assertFrets(9, "major", [-1, 0, 2, 2, 2, 0], "A")
assertFrets(4, "major", [0, 2, 2, 1, 0, 0], "E")
assertFrets(2, "minor", [-1, -1, 0, 2, 3, 1], "Dm")
assertFrets(4, "minor", [0, 2, 2, 0, 0, 0], "Em")
assertFrets(9, "minor", [-1, 0, 2, 2, 1, 0], "Am")
assertEq(tabBlock(voicingFor(0, "major")), "e|--0--\nB|--1--\nG|--0--\nD|--2--\nA|--3--\nE|--x--")
assertEq(tabBlock(null), "e|-----\nB|-----\nG|-----\nD|-----\nA|-----\nE|-----")
assertEq(tabBlock(voicingFor(0, "major"), "vertical"), "E A D G B e\nx 3 2 0 1 0")
assertEq(tabBlock(null, "vertical"), "E A D G B e\n- - - - - -")
assertEq(tabLines(voicingFor(0, "major"), "vertical")[0].name, "E")
assertEq(tabLines(voicingFor(0, "major"), "vertical")[5].name, "e")
assertEq(WHITE_KEYS_C3_C5, 15)
assertEq(pianoKeysC3C5().filter(function (k) { return k.type === "white" }).length, 15)
assertEq(pianoKeysC3C5().length, 25)
var qualities = ["major", "minor", "diminished", "augmented"]
var qi
var pc
for (qi = 0; qi < qualities.length; qi++) {
  for (pc = 0; pc < 12; pc++) {
    var found = voicingFor(pc, qualities[qi])
    assert(found.frets.length === 6, qualities[qi] + " " + pc + " has 6 strings")
    assert(coversChord(found.frets, pc, qualities[qi]), qualities[qi] + " " + pc + " voicing")
  }
}

// Parallel-mode colour grid.
var cPhryg2 = scaleNotes(0, 5)[1]
assertEq(cPhryg2.name, "Db", "C Phrygian 2nd is Db not C#")
var cLyd4 = scaleNotes(0, 0)[3]
assertEq(cLyd4.name, "F#", "C Lydian 4th is F#")
var ionianI = cellChord(0, 1, 0, false)
assertEq(ionianI.symbol, "C")
assertEq(romanNumeral(ionianI, 0, 1), "I")
var mixoI7 = cellChord(0, 2, 0, true)
assertEq(mixoI7.symbol, "C7", "Mixolydian tonic is dominant 7")
var ionianI7 = cellChord(0, 1, 0, true)
assertEq(ionianI7.symbol, "Cmaj7", "Ionian tonic is major 7")
var aeolian6 = cellChord(0, 4, 5, false)
assertEq(romanNumeral(aeolian6, 0, 1), "♭VI", "Aeolian vi relative to Ionian home")
var locTonic = cellChord(0, 6, 0, false)
assert(locTonic.unstableTonic, "Locrian tonic is diminished")
var grid4 = buildGrid(0, 1, false, false)
assertEq(grid4.length, 4, "compact view shows four modes")
var grid7 = buildGrid(0, 1, false, true)
assertEq(grid7.length, 7)
var fCount = 0
var r, c
for (r = 0; r < grid7.length; r++) {
  for (c = 0; c < grid7[r].cells.length; c++) {
    if (grid7[r].cells[c].chord.symbol === "F")
      fCount++
  }
}
assertEq(fCount, 3, "F major appears in three mode rows on C root")
var shifted = shiftProgressionRows(
  [{ modeIndex: 1, degreeIndex: 0 }, { modeIndex: 1, degreeIndex: 3 }], 1)
assertEq(shifted[0].modeIndex, 2)
assertEq(shifted[1].degreeIndex, 3)
assertEq(sharedToneCount(ionianI, cellChord(0, 1, 3, false)), 1)
assertEq(visibleModeCount(false), 4)
assertEq(visibleModeCount(true), 7)
assertEq(visibleModeIndex(0, false), 1)
assertEq(modeAbbrev(1), "Ion")
var infoAeo6 = cellInfo(0, 4, 5, 1, false, 3)
assertEq(infoAeo6.symbol, "Ab")
assertEq(infoAeo6.numeral, "♭VI")
var dropC = decodeChord(encodeChord(toTriadPayload(ionianI)))
assertEq(dropC.rootPc, 0)
assertEq(dropC.quality, "major")
var dropLoc = decodeChord(encodeChord(toTriadPayload(locTonic)))
assertEq(dropLoc.rootPc, 0)
assertEq(dropLoc.quality, "diminished")
var dropAeolian = decodeChord(encodeChord(toTriadPayload(aeolian6)))
assertEq(dropAeolian.rootPc, 8)
assertEq(dropAeolian.quality, "major")
